// MIT License
//
// Copyright (c) 2025 kubernetes-bifrost
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: bifrost.proto

package bifröstpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerRegistryLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerRegistryLogin) Reset() {
	*x = ContainerRegistryLogin{}
	mi := &file_bifrost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRegistryLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRegistryLogin) ProtoMessage() {}

func (x *ContainerRegistryLogin) ProtoReflect() protoreflect.Message {
	mi := &file_bifrost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRegistryLogin.ProtoReflect.Descriptor instead.
func (*ContainerRegistryLogin) Descriptor() ([]byte, []int) {
	return file_bifrost_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerRegistryLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ContainerRegistryLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ContainerRegistryLogin) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_bifrost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bifrost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_bifrost_proto_rawDescGZIP(), []int{1}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_bifrost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bifrost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_bifrost_proto_rawDescGZIP(), []int{2}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetTokenRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ContainerRegistry string                 `protobuf:"bytes,1,opt,name=container_registry,json=containerRegistry,proto3" json:"container_registry,omitempty"`
	// Types that are valid to be assigned to ProviderParams:
	//
	//	*GetTokenRequest_GCP
	ProviderParams isGetTokenRequest_ProviderParams `protobuf_oneof:"provider_params"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_bifrost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bifrost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_bifrost_proto_rawDescGZIP(), []int{3}
}

func (x *GetTokenRequest) GetContainerRegistry() string {
	if x != nil {
		return x.ContainerRegistry
	}
	return ""
}

func (x *GetTokenRequest) GetProviderParams() isGetTokenRequest_ProviderParams {
	if x != nil {
		return x.ProviderParams
	}
	return nil
}

func (x *GetTokenRequest) GetGCP() *GCPParams {
	if x != nil {
		if x, ok := x.ProviderParams.(*GetTokenRequest_GCP); ok {
			return x.GCP
		}
	}
	return nil
}

type isGetTokenRequest_ProviderParams interface {
	isGetTokenRequest_ProviderParams()
}

type GetTokenRequest_GCP struct {
	GCP *GCPParams `protobuf:"bytes,2,opt,name=GCP,proto3,oneof"`
}

func (*GetTokenRequest_GCP) isGetTokenRequest_ProviderParams() {}

type GetTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Token:
	//
	//	*GetTokenResponse_RegistryLogin
	//	*GetTokenResponse_GCP
	Token         isGetTokenResponse_Token `protobuf_oneof:"token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_bifrost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bifrost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_bifrost_proto_rawDescGZIP(), []int{4}
}

func (x *GetTokenResponse) GetToken() isGetTokenResponse_Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *GetTokenResponse) GetRegistryLogin() *ContainerRegistryLogin {
	if x != nil {
		if x, ok := x.Token.(*GetTokenResponse_RegistryLogin); ok {
			return x.RegistryLogin
		}
	}
	return nil
}

func (x *GetTokenResponse) GetGCP() *GCPToken {
	if x != nil {
		if x, ok := x.Token.(*GetTokenResponse_GCP); ok {
			return x.GCP
		}
	}
	return nil
}

type isGetTokenResponse_Token interface {
	isGetTokenResponse_Token()
}

type GetTokenResponse_RegistryLogin struct {
	RegistryLogin *ContainerRegistryLogin `protobuf:"bytes,1,opt,name=registry_login,json=registryLogin,proto3,oneof"`
}

type GetTokenResponse_GCP struct {
	GCP *GCPToken `protobuf:"bytes,2,opt,name=GCP,proto3,oneof"`
}

func (*GetTokenResponse_RegistryLogin) isGetTokenResponse_Token() {}

func (*GetTokenResponse_GCP) isGetTokenResponse_Token() {}

type GCPParams struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	WorkloadIdentityProvider string                 `protobuf:"bytes,1,opt,name=workloadIdentityProvider,proto3" json:"workloadIdentityProvider,omitempty"`
	ServiceAccountEmail      string                 `protobuf:"bytes,2,opt,name=serviceAccountEmail,proto3" json:"serviceAccountEmail,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GCPParams) Reset() {
	*x = GCPParams{}
	mi := &file_bifrost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCPParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCPParams) ProtoMessage() {}

func (x *GCPParams) ProtoReflect() protoreflect.Message {
	mi := &file_bifrost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCPParams.ProtoReflect.Descriptor instead.
func (*GCPParams) Descriptor() ([]byte, []int) {
	return file_bifrost_proto_rawDescGZIP(), []int{5}
}

func (x *GCPParams) GetWorkloadIdentityProvider() string {
	if x != nil {
		return x.WorkloadIdentityProvider
	}
	return ""
}

func (x *GCPParams) GetServiceAccountEmail() string {
	if x != nil {
		return x.ServiceAccountEmail
	}
	return ""
}

type GCPToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Expiry        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCPToken) Reset() {
	*x = GCPToken{}
	mi := &file_bifrost_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCPToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCPToken) ProtoMessage() {}

func (x *GCPToken) ProtoReflect() protoreflect.Message {
	mi := &file_bifrost_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCPToken.ProtoReflect.Descriptor instead.
func (*GCPToken) Descriptor() ([]byte, []int) {
	return file_bifrost_proto_rawDescGZIP(), []int{6}
}

func (x *GCPToken) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GCPToken) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *GCPToken) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GCPToken) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *GCPToken) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_bifrost_proto protoreflect.FileDescriptor

const file_bifrost_proto_rawDesc = "" +
	"\n" +
	"\rbifrost.proto\x12\n" +
	"bifrost.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x8b\x01\n" +
	"\x16ContainerRegistryLogin\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x13\n" +
	"\x11GetVersionRequest\".\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"~\n" +
	"\x0fGetTokenRequest\x12-\n" +
	"\x12container_registry\x18\x01 \x01(\tR\x11containerRegistry\x12)\n" +
	"\x03GCP\x18\x02 \x01(\v2\x15.bifrost.v1.GCPParamsH\x00R\x03GCPB\x11\n" +
	"\x0fprovider_params\"\x92\x01\n" +
	"\x10GetTokenResponse\x12K\n" +
	"\x0eregistry_login\x18\x01 \x01(\v2\".bifrost.v1.ContainerRegistryLoginH\x00R\rregistryLogin\x12(\n" +
	"\x03GCP\x18\x02 \x01(\v2\x14.bifrost.v1.GCPTokenH\x00R\x03GCPB\a\n" +
	"\x05token\"y\n" +
	"\tGCPParams\x12:\n" +
	"\x18workloadIdentityProvider\x18\x01 \x01(\tR\x18workloadIdentityProvider\x120\n" +
	"\x13serviceAccountEmail\x18\x02 \x01(\tR\x13serviceAccountEmail\"\xc4\x01\n" +
	"\bGCPToken\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x122\n" +
	"\x06expiry\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x05 \x01(\x03R\texpiresIn2\xc5\x01\n" +
	"\aBifrost\x12`\n" +
	"\n" +
	"GetVersion\x12\x1d.bifrost.v1.GetVersionRequest\x1a\x1e.bifrost.v1.GetVersionResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/version\x12X\n" +
	"\bGetToken\x12\x1b.bifrost.v1.GetTokenRequest\x1a\x1c.bifrost.v1.GetTokenResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/tokenB:Z8github.com/kubernetes-bifrost/bifrost/grpc/go;bifröstpbb\x06proto3"

var (
	file_bifrost_proto_rawDescOnce sync.Once
	file_bifrost_proto_rawDescData []byte
)

func file_bifrost_proto_rawDescGZIP() []byte {
	file_bifrost_proto_rawDescOnce.Do(func() {
		file_bifrost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bifrost_proto_rawDesc), len(file_bifrost_proto_rawDesc)))
	})
	return file_bifrost_proto_rawDescData
}

var file_bifrost_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bifrost_proto_goTypes = []any{
	(*ContainerRegistryLogin)(nil), // 0: bifrost.v1.ContainerRegistryLogin
	(*GetVersionRequest)(nil),      // 1: bifrost.v1.GetVersionRequest
	(*GetVersionResponse)(nil),     // 2: bifrost.v1.GetVersionResponse
	(*GetTokenRequest)(nil),        // 3: bifrost.v1.GetTokenRequest
	(*GetTokenResponse)(nil),       // 4: bifrost.v1.GetTokenResponse
	(*GCPParams)(nil),              // 5: bifrost.v1.GCPParams
	(*GCPToken)(nil),               // 6: bifrost.v1.GCPToken
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_bifrost_proto_depIdxs = []int32{
	7, // 0: bifrost.v1.ContainerRegistryLogin.expires_at:type_name -> google.protobuf.Timestamp
	5, // 1: bifrost.v1.GetTokenRequest.GCP:type_name -> bifrost.v1.GCPParams
	0, // 2: bifrost.v1.GetTokenResponse.registry_login:type_name -> bifrost.v1.ContainerRegistryLogin
	6, // 3: bifrost.v1.GetTokenResponse.GCP:type_name -> bifrost.v1.GCPToken
	7, // 4: bifrost.v1.GCPToken.expiry:type_name -> google.protobuf.Timestamp
	1, // 5: bifrost.v1.Bifrost.GetVersion:input_type -> bifrost.v1.GetVersionRequest
	3, // 6: bifrost.v1.Bifrost.GetToken:input_type -> bifrost.v1.GetTokenRequest
	2, // 7: bifrost.v1.Bifrost.GetVersion:output_type -> bifrost.v1.GetVersionResponse
	4, // 8: bifrost.v1.Bifrost.GetToken:output_type -> bifrost.v1.GetTokenResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_bifrost_proto_init() }
func file_bifrost_proto_init() {
	if File_bifrost_proto != nil {
		return
	}
	file_bifrost_proto_msgTypes[3].OneofWrappers = []any{
		(*GetTokenRequest_GCP)(nil),
	}
	file_bifrost_proto_msgTypes[4].OneofWrappers = []any{
		(*GetTokenResponse_RegistryLogin)(nil),
		(*GetTokenResponse_GCP)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bifrost_proto_rawDesc), len(file_bifrost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bifrost_proto_goTypes,
		DependencyIndexes: file_bifrost_proto_depIdxs,
		MessageInfos:      file_bifrost_proto_msgTypes,
	}.Build()
	File_bifrost_proto = out.File
	file_bifrost_proto_goTypes = nil
	file_bifrost_proto_depIdxs = nil
}
